version: "3.8"

services:
  app:
    build: .
    ports:
      - "8085:8085"
    environment:
      - PORT=:8085
      - DATABASE_URL=postgres://user:password@db:5432/myapp?sslmode=disable
      - JWT_SECRET=your-very-secure-secret-key
    depends_on:
      - db

  db:
    image: "postgres:14.2"
    environment:
      POSTGRES_DB: bee
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
